---
# tasks file for docker-registry
- name: DockerHub Login
  docker_login:
    username: nourdziri
    password: 21238899@
    email: nourdziri5@gmail.com
- name: Tag and push to docker hub
  docker_image:
    name: devops
    repository: nourdziri/lab_cd
    push: yes
    source: local
