---
# tasks file for docker-registry
- name: DockerHub Login
  docker_login:
    username: nourdziri
    password: 21238899@
    email: nourdziri5@gmail.com
- name: Push to docker hub
  docker_image:
    name: "devops"
    repository: nour752/lab1_cd
    push: yes
    tag: latest
